@startuml
class ml.alessiomanai.streamingtv.utils.WebViewSettings {
+ {static} WebView doSettings(WebView)
}
class ml.alessiomanai.streamingtv.connessione.WebRequest {
+ {static} int GET
+ {static} int POST
+ String makeWebServiceCall(String,int)
+ String makeWebServiceCall(String,int,HashMap<String,String>)
}
class ml.alessiomanai.streamingtv.MainActivity {
~ Button foodNetwork
~ Button radioItaliaTv
~ Button videolina
~ Button canale5
~ Button tv8
~ Button italia1
~ Button topcrime
~ Button giallo
~ Button rete4
~ Button iris
~ String JSON_URL
- ArrayList<JSONObject> finalListaCanali
# void onCreate(Bundle)
- void startChannel(String)
- void noInternet(Context)
- ArrayList<JSONObject> caricaCanali()
}
class ml.alessiomanai.streamingtv.connessione.ChannelUpdaterCallable {
+ ArrayList<JSONObject> getAssetJsonData(String)
+ ArrayList<JSONObject> call()
}
class ml.alessiomanai.streamingtv.ChannelExoPlayer {
- ExoPlayer player
# void onCreate(Bundle)
# void onDestroy()
}
class ml.alessiomanai.streamingtv.ExampleInstrumentedTest {
+ void useAppContext()
}
class ml.alessiomanai.streamingtv.utils.M3u8Reader {
+ {static} String getHtmlReader(String)
}
class ml.alessiomanai.streamingtv.ExampleUnitTest {
+ void addition_isCorrect()
}
class ml.alessiomanai.streamingtv.canali.ChannelInterface {
# void onCreate(Bundle)
}


androidx.appcompat.app.AppCompatActivity <|-- ml.alessiomanai.streamingtv.MainActivity
java.util.concurrent.Callable <|.. ml.alessiomanai.streamingtv.connessione.ChannelUpdaterCallable
androidx.appcompat.app.AppCompatActivity <|-- ml.alessiomanai.streamingtv.ChannelExoPlayer
androidx.appcompat.app.AppCompatActivity <|-- ml.alessiomanai.streamingtv.canali.ChannelInterface
@enduml